### ISSUE TITLE
Fix inlang primary color not being used in primary buttons

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-message-ui-components#21]
### Context

Watch the LOOM
[https://www.loom.com/share/d75defdb96e3483db516426e95799e30](https://www.loom.com/share/d75defdb96e3483db516426e95799e30)

### Proposal

Fix primary color to be used in primary button.

**Comment by NilsJacobsen** [comment]
Current strategy:

In order to not need to pass in 10 primary shades for shoelace, we decided to pass in the primary-500 and calculate the oder shades.

Shoelace is using the primary-600 here to keep enough contrast to the white color.  What makes sense in my eyes. We can not garanty the contrast to be sufficiant if we use 500 (for example for orange …)

VS-code is doing it's own game here allowing low contrast and wild colors. Which should not give huge requirements to other apps.

Having a slightly darker color in favor of contrast feels ok for me. 

@felix.haeberle you could make the case that the primary color appears in 80% of the cases on buttons. So that should match. Then we need to adjust the calculation to use the primary-600 as an anchor. With the downside of having less good contrast in the lower contrast themes on CS-Code, but we also don't want to optimize for them right?

**Comment by felixhaeberle** [comment]
Is there a way to control the button color separately? I also thought about directly setting primary 600 in Sherlock. But then, we circumventing the calculation 😅

**Comment by NilsJacobsen** [comment]
Nope, not possible, but the more I think about it, the more I think, that we may want to let the app-devs pass in a primary-600 and describe it as a color that has good contrast with white font in the docs.

**Comment by NilsJacobsen** [comment]
Update:

* Primary color is most often used as surface with white text on it. We let app-devs pass this color in with the annotation, that there need to be enough contrast for white text on this colored primary surface.
* Under the hood we assign this color to the primary-600 and calculate the rest (makes more sense then 500)
* If you have issue with that, you can still use the shoelace css properties itself and override all 10 shades of primary

**Comment by NilsJacobsen** [comment]
@felix.haeberle can you confirm that the color should be correct now?

**Comment by felixhaeberle** [comment]
Confirmed 👍
